replicaCount: 2

image:
  repository: simple-app
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi
    